In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
df = pd.read_csv('city.csv')
df

city  area     price
0      Karnal  2600   5500000
1      Karnal  3000   5650000
2      Karnal  3600   6100000
3      Karnal  2600   6800000
4      Mohali  2800   5850000
5      Mohali  3200   6150000
6      Mohali  3300   6500000
7      Mohali  3600   7100000
8   Panchkula  2600   5750000
9   Panchkula  2900   6000000
10  Panchkula  3100   6200000
11  Panchkula  3600  69500000

In [2]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [3]:
# dfle = encoder.fit_transform(df.city)
# dfle

array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2])

In [6]:
dfle = df
dfle.city = encoder.fit_transform(df.city)
dfle

city  area     price
0      0  2600   5500000
1      0  3000   5650000
2      0  3600   6100000
3      0  2600   6800000
4      1  2800   5850000
5      1  3200   6150000
6      1  3300   6500000
7      1  3600   7100000
8      2  2600   5750000
9      2  2900   6000000
10     2  3100   6200000
11     2  3600  69500000

In [8]:
x = dfle[['city','area']].values
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3600],
       [   0, 2600],
       [   1, 2800],
       [   1, 3200],
       [   1, 3300],
       [   1, 3600],
       [   2, 2600],
       [   2, 2900],
       [   2, 3100],
       [   2, 3600]], dtype=int64)

In [10]:
y = dfle.price.values
y

array([ 5500000,  5650000,  6100000,  6800000,  5850000,  6150000,
        6500000,  7100000,  5750000,  6000000,  6200000, 69500000],
      dtype=int64)

In [11]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [12]:
model.coef_

array([6993345.86466166,   18633.08270677])

In [13]:
model.intercept_

-52865075.18796997