In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
df = pd.read_csv('realestate.csv')
df

area  bedroom  age   price
0  2600      3.0   20  600000
1  3000      4.0   15  650000
2  3600      3.0   30  595000
3  3200      NaN   18  610000
4  4000      5.0    8  760000

In [3]:
df.bedroom.median()

3.5

In [4]:
df.bedroom = df.bedroom.fillna(df.bedroom.median())
df

area  bedroom  age   price
0  2600      3.0   20  600000
1  3000      4.0   15  650000
2  3600      3.0   30  595000
3  3200      3.5   18  610000
4  4000      5.0    8  760000

In [5]:
model=linear_model.LinearRegression()
new_df = df.drop('price', axis='columns')
model.fit(new_df, df.price)

LinearRegression()

In [6]:
model.predict([[3000,3,10]])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([612315.96295715])

In [7]:
model.coef_

array([ 2.65087898e+01,  5.43297755e+04, -1.80113012e+03])

In [10]:
model.intercept_

387811.56804269284

In [11]:
import pickle
with open('trainedmodel','wb') as file:
    pickle.dump(model,file)

In [12]:
with open ('trainedmodel', 'rb') as f:
    tm = pickle.load(f)

In [13]:
tm.coef_

array([ 2.65087898e+01,  5.43297755e+04, -1.80113012e+03])

In [14]:
import joblib
joblib.dump(model, 'model_joblib')

['model_joblib']

In [15]:
jl = joblib.load('model_joblib')

In [16]:
jl.coef_

array([ 2.65087898e+01,  5.43297755e+04, -1.80113012e+03])

In [17]:
jl.intercept_

387811.56804269284

In [18]:
model.predict([[3000,3,10]])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([612315.96295715])